# -*- coding: utf-8 -*-
"""Linear_regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NPRcmnel8f8BRvXzOrsn-Fpd7N_dokwc
"""

import pandas as pd
from sklearn.datasets import fetch_california_housing

california=fetch_california_housing()
df_x=pd.DataFrame(california.data,columns=california.feature_names)
df_y=pd.DataFrame(california.target,columns=['Price'])

df_x.head()

df_x.info()

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df_x,df_y,test_size=0.2)

#standardize the data
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(x_train)
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)

#linear regression
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(x_train,y_train)

#evaluate the model
model.score(x_test,y_test)

model.coef_,model.intercept_